# Generated by Django 2.2.4 on 2019-08-23 13:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('sentiment_analysis', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('topic_extraction', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('categorization', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('force_analysis', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
