# Generated by Django 2.2.4 on 2019-10-22 13:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='categorization_raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="From Meaningcloud's Deep Categorization", null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='sentiment_analysis_raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="From MeaningCloud's Sentiment Analysis", null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='topic_extraction_raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="From MeaningCloud's Topic Extraction", null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='categorization',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="SERIALIZED: From MeaningCloud's Deep Categorization", null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='sentiment_analysis',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="SERIALIZED: From MeaningCloud's Sentiment Analysis", null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='topic_extraction',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="SERIALIZED: From MeaningCloud's Topic Extraction", null=True),
        ),
    ]
